# fly.toml app configuration file generated for fullstack-blog-app on 2024-08-02T17:28:13+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fullstack-blog-app'
primary_region = 'arn'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
